# Threat Intelligence Lists
SUSPICIOUS_TLDS = ['.top', '.xyz', '.biz', '.zip']
HIGH_RISK_KEYWORDS = ['verify', 'login', 'bank', 'secure', 'account']
HIGH_VALUE_TARGETS = ['google', 'amazon', 'paypal', 'github', 'microsoft', 'apple']
SUSPICIOUS_KEYWORDS = ["free", "login", "update", "verify", "secure", "account"]

# Scoring Thresholds
NEW_DOMAIN_THRESHOLD_DAYS = 30
NEWLY_REGISTERED_DAYS = 14
RECENTLY_REGISTERED_DAYS = 90
MAX_REDIRECT_HOPS_FREE = 3
SEVERE_VENDOR_FLAGS_THRESHOLD = 5

VERDICT_RED_THRESHOLD = 71
VERDICT_YELLOW_THRESHOLD = 36
PUNYCODE_MIN_SCORE = 75
BRAND_PENALTY_SCORE = 50
SYNERGY_PENALTY_SCORE = 40
REDIRECT_CHAIN_MAJOR_PENALTY = 20
REDIRECT_CHAIN_MINOR_PENALTY = 5
VENDOR_FLAG_PENALTY = 40
NEWLY_REGISTERED_PENALTY = 40
RECENTLY_REGISTERED_PENALTY = 20
TYPOSQUATTING_PENALTY = 50

# Fallbacks
DEFAULT_DOMAIN_AGE_DAYS = 3000
TOTAL_VENDORS_COUNT = 70
